[build]
  command = "npm run build"
  publish = ".next"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[build.environment]
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"

# Redirects untuk SSR
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs/:splat"
  status = 200

# Headers untuk caching (REPLACE headers di next.config)
[[headers]]
  for = "/sitemap.xml"
  [headers.values]
    Cache-Control = "public, max-age=3600, stale-while-revalidate=86400"

[[headers]]
  for = "/robots.txt"
  [headers.values]
    Cache-Control = "public, max-age=3600, stale-while-revalidate=86400"

[[headers]]
  for = "/_next/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Handle 404
[[redirects]]
  from = "/*"
  to = "/.netlify/functions/nextjs/404"
  status = 404
  conditions = { status = "404" }
